### ISSUE TITLE
Prereq declaration insufficient

### ISSUE THREAD

**Issue by andk** [oalders/webservice-sqlformat#1]
It says it recommends LWP::ConsoleLogger::Easy 0.000028, but the test fails when L:C:E is lower.

Sample fail report:

http://www.cpantesters.org/cpan/report/70756972

If a test fails without it, it is either a requirement or the test is too demanding, right?

Best,

**Comment by oalders** [comment]
Hi @andk,

Thanks very much for this.  :)  Should now be fixed via ec6f91fe37298.  I've uploaded a new release.

Best,

Olaf
